language: python

sudo: no

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --name hydra --yes python=$TRAVIS_PYTHON_VERSION
  - source activate hydra
  - conda install --yes setuptools numpy scipy pillow nose
  - conda install --yes -c conda-forge python-coveralls coverage
  - python setup.py install

script:
  - nosetests --nocapture --with-coverage --cover-package=hydra --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

branches:
  only:
    - master
    - development

notifications:
  email:
    recepients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
